name: CraigsFirstSite
favicon: null
layout_spectrum: 0
typography_spectrum: 0.94511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 1
  lightness: 0.5034052063710988
  saturation: 0.6886503838468343
  rhythmicContrast: 0.739647188456729
purpose: []
